// /lib/emailSender.ts

import * as nodemailer from 'nodemailer';

// 1. Create a Transporter (the connection to Mailtrap)
// The transporter is configured once and reused for all emails.
// It securely reads the credentials from your .env.local file.
const transporter = nodemailer.createTransport({
    host: process.env.MAILTRAP_HOST,
    // Port 587 uses STARTTLS, port 2525 is alternative, port 465 uses SSL/TLS
    port: parseInt(process.env.MAILTRAP_PORT || '587'),
    secure: false, // false for STARTTLS (587/2525), true for SSL/TLS (465)
    auth: {
        user: process.env.MAILTRAP_USER,
        pass: process.env.MAILTRAP_PASS,
    },
});

/**
 * Sends a custom email containing the secure invite link to the approved agent.
 * @param recipientEmail The agent's email address.
 * @param inviteLink The secure action link generated by supabaseAdmin.auth.admin.generateLink().
 */
export async function sendInviteLinkEmail(recipientEmail: string, inviteLink: string) {

    // 2. Define the email content
    const mailOptions = {
        // Must be a valid email address (e.g., matching the Sender Email in Supabase Auth settings)
        from: 'no-reply@arkalliance.com',
        to: recipientEmail,
        subject: '🎉 ArkAlliance Account Approved: Set Your Password',
        html: `
            <div style="font-family: Arial, sans-serif; line-height: 1.6;">
                <h1>Welcome to ArkAlliance!</h1>
                <p>Your account has been **approved** by our administration team. You can now set your permanent password and log in to the portal.</p>
                
                <p>Click the secure link below to proceed:</p>
                
                <a href="${inviteLink}" 
                   style="display: inline-block; background-color: #007bff; color: white; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: bold;">
                    Set Your Password & Login
                </a>
                
                <p style="margin-top: 20px;">The link is **single-use** and valid for a short time. If you have trouble, please contact support.</p>
            </div>
        `,
    };

    // 3. Send the email
    try {
        const info = await transporter.sendMail(mailOptions);
        console.log(`Invite email sent successfully to ${recipientEmail}. Message ID: ${info.messageId}`);
        return { success: true, messageId: info.messageId };
    } catch (error: any) {
        console.error(`Error sending email to ${recipientEmail}:`, error);
        // Return a clear failure signal for the calling Admin action
        return { success: false, error: error.message };
    }

}

/**
     * Sends a rejection email to the supplier.
     * @param recipientEmail The supplier's email address.
     * @param reason The reason for rejection.
     */
export async function sendRejectionEmail(recipientEmail: string, reason?: string) {
    const mailOptions = {
        from: 'no-reply@arkalliance.com',
        to: recipientEmail,
        subject: 'Account Status Update - ArkAlliance',
        html: `
            <div style="font-family: Arial, sans-serif; line-height: 1.6;">
                <h1>Account Application Update</h1>
                <p>Thank you for your interest in ArkAlliance. We have reviewed your supplier application.</p>
                <p>Unfortunately, we are unable to approve your account at this time.</p>
                
                ${reason ? `<div style="background-color: #f8f9fa; border-left: 4px solid #dc3545; padding: 15px; margin: 20px 0;"><strong>Reason:</strong><br/>${reason}</div>` : ''}

                <p><strong>Refund Status:</strong> A full refund for your subscription payment has been initiated. It may take 5-10 business days to appear on your statement.</p>
                
                <p>If you believe this decision was made in error or if you have addressed the issues mentioned, please contact our support team.</p>
            </div>
        `,
    };

    try {
        const info = await transporter.sendMail(mailOptions);
        console.log(`Rejection email sent successfully to ${recipientEmail}. Message ID: ${info.messageId}`);
        return { success: true, messageId: info.messageId };
    } catch (error: any) {
        console.error(`Error sending rejection email to ${recipientEmail}:`, error);
        return { success: false, error: error.message };
    }
}
