// /lib/emailSender.ts

import * as nodemailer from 'nodemailer';

// 1. Create a Transporter (the connection to Mailtrap)
// The transporter is configured once and reused for all emails.
// It securely reads the credentials from your .env.local file.
const transporter = nodemailer.createTransport({
    host: process.env.MAILTRAP_HOST,
    // Port 587 uses STARTTLS, port 2525 is alternative, port 465 uses SSL/TLS
    port: parseInt(process.env.MAILTRAP_PORT || '587'),
    secure: false, // false for STARTTLS (587/2525), true for SSL/TLS (465)
    auth: {
        user: process.env.MAILTRAP_USER,
        pass: process.env.MAILTRAP_PASS,
    },
});

/**
 * Sends a custom email containing the secure invite link to the approved agent.
 * @param recipientEmail The agent's email address.
 * @param inviteLink The secure action link generated by supabaseAdmin.auth.admin.generateLink().
 */
export async function sendInviteLinkEmail(recipientEmail: string, inviteLink: string) {

    // 2. Define the email content
    const mailOptions = {
        // Must be a valid email address (e.g., matching the Sender Email in Supabase Auth settings)
        from: 'no-reply@arkalliance.com',
        to: recipientEmail,
        subject: '🎉 ArkAlliance Account Approved: Set Your Password',
        html: `
            <div style="font-family: Arial, sans-serif; line-height: 1.6;">
                <h1>Welcome to ArkAlliance!</h1>
                <p>Your account has been **approved** by our administration team. You can now set your permanent password and log in to the portal.</p>
                
                <p>Click the secure link below to proceed:</p>
                
                <a href="${inviteLink}" 
                   style="display: inline-block; background-color: #007bff; color: white; padding: 12px 25px; text-decoration: none; border-radius: 6px; font-weight: bold;">
                    Set Your Password & Login
                </a>
                
                <p style="margin-top: 20px;">The link is **single-use** and valid for a short time. If you have trouble, please contact support.</p>
            </div>
        `,
    };

    // 3. Send the email
    try {
        const info = await transporter.sendMail(mailOptions);
        console.log(`Invite email sent successfully to ${recipientEmail}. Message ID: ${info.messageId}`);
        return { success: true, messageId: info.messageId };
    } catch (error: any) {
        console.error(`Error sending email to ${recipientEmail}:`, error);
        // Return a clear failure signal for the calling Admin action
        return { success: false, error: error.message };
    }

}

/**
     * Sends a rejection email to the supplier.
     * @param recipientEmail The supplier's email address.
     * @param reason The reason for rejection.
     */
export async function sendRejectionEmail(recipientEmail: string, reason?: string) {
    const mailOptions = {
        from: 'no-reply@arkalliance.com',
        to: recipientEmail,
        subject: 'Account Status Update - ArkAlliance',
        html: `
            <div style="font-family: Arial, sans-serif; line-height: 1.6;">
                <h1>Account Application Update</h1>
                <p>Thank you for your interest in ArkAlliance. We have reviewed your supplier application.</p>
                <p>Unfortunately, we are unable to approve your account at this time.</p>
                
                ${reason ? `<div style="background-color: #f8f9fa; border-left: 4px solid #dc3545; padding: 15px; margin: 20px 0;"><strong>Reason:</strong><br/>${reason}</div>` : ''}

                <p><strong>Refund Status:</strong> A full refund for your subscription payment has been initiated. It may take 5-10 business days to appear on your statement.</p>
                
                <p>If you believe this decision was made in error or if you have addressed the issues mentioned, please contact our support team.</p>
            </div>
        `,
    };

    try {
        const info = await transporter.sendMail(mailOptions);
        console.log(`Rejection email sent successfully to ${recipientEmail}. Message ID: ${info.messageId}`);
        return { success: true, messageId: info.messageId };
    } catch (error: any) {
        console.error(`Error sending rejection email to ${recipientEmail}:`, error);
        return { success: false, error: error.message };
    }
}

/**
 * Sends a payment confirmation email to the supplier (Administrator Review Phase).
 * @param recipientEmail The supplier's email address.
 * @param supplierName The supplier's company name or contact name.
 */
export async function sendPaymentConfirmationEmail(recipientEmail: string, supplierName: string) {
    const mailOptions = {
        from: 'no-reply@arkalliance.com',
        to: recipientEmail,
        subject: 'Payment Confirmed! Your ArkAlliance Supplier Profile is Under Review',
        html: `
            <div style="font-family: Arial, sans-serif; line-height: 1.6;">
                <h1>Payment Confirmed</h1>
                <p>Dear ${supplierName},</p>
                <p>Thank you! We have successfully processed your payment for the Supplier Subscription.</p>
                
                <p><strong>Note:</strong> Your official payment receipt will be sent to this email address directly from Stripe once your account is fully activated and out of testing mode.</p>

                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">

                <h2>What Happens Next?</h2>
                <p>Your registration has now moved into our manual administrative review queue. Our team will verify your details within <strong>48 hours</strong>.</p>
                
                <p>You do not need to take any further action at this time.</p>

                <p><strong>Access to Portal:</strong><br/>
                Once your profile is approved, you will receive a separate email containing your final login link. You will not be able to access the portal until this approval is complete.</p>
                
                <p style="margin-top: 30px; font-size: 0.9em; color: #666;">If you have any questions, please reply to this email.</p>
            </div>
        `,
    };

    try {
        const info = await transporter.sendMail(mailOptions);
        console.log(`Payment confirmation email sent locally to Mailtrap for ${recipientEmail}. Message ID: ${info.messageId}`);
        return { success: true, messageId: info.messageId };
    } catch (error: any) {
        console.error(`Error sending payment confirmation to ${recipientEmail}:`, error);
        return { success: false, error: error.message };
    }
}

/**
 * Sends a subscription update notification to the supplier.
 * @param recipientEmail The supplier's email address.
 * @param updateType The type of update ('plan_change', 'pause', 'resume', 'cancel').
 * @param details Object containing details like new slot count, end date, etc.
 */
export async function sendSubscriptionUpdateEmail(
    recipientEmail: string,
    updateType: 'plan_change' | 'pause' | 'resume' | 'cancel',
    details: { newSlotCount?: number, endDate?: string, companyName?: string }
) {
    const companyName = details.companyName || 'Valued Partner';
    let subject = 'Subscription Update - ArkAlliance';
    let content = '';

    const formattedDate = details.endDate ? new Date(details.endDate).toLocaleDateString() : 'the end of the billing cycle';

    switch (updateType) {
        case 'plan_change':
            subject = 'Plan Updated - ArkAlliance';
            content = `
                <p>Your subscription plan has been successfully updated.</p>
                <p><strong>New Slot Count:</strong> ${details.newSlotCount}</p>
                <p>Any prorated charges or credits will be applied to your next invoice.</p>
            `;
            break;
        case 'pause':
            subject = 'Subscription Paused - ArkAlliance';
            content = `
                <p>Your subscription has been scheduled to <strong>PAUSE</strong>.</p>
                <p><strong>Effective Date:</strong> ${formattedDate}</p>
                <p>Your products will remain visible until this date. After this date, your listings will be hidden and you will not be billed.</p>
                <p>You can resume your subscription at any time from your dashboard.</p>
            `;
            break;
        case 'resume':
            subject = 'Subscription Resumed - ArkAlliance';
            content = `
                <p>Great news! Your subscription has been <strong>RESUMED</strong>.</p>
                <p>Your listings are now active and visible on the marketplace.</p>
            `;
            break;
        case 'cancel':
            subject = 'Subscription Cancelled - ArkAlliance';
            content = `
                <p>Your subscription has been cancelled.</p>
                <p>Your access will continue until <strong>${formattedDate}</strong>.</p>
                <p>We're sorry to see you go. If you change your mind, you can resubscribe from your dashboard.</p>
            `;
            break;
    }

    const mailOptions = {
        from: 'no-reply@arkalliance.com',
        to: recipientEmail,
        subject: subject,
        html: `
            <div style="font-family: Arial, sans-serif; line-height: 1.6; color: #333;">
                <h1>Subscription Update</h1>
                <p>Dear ${companyName},</p>
                ${content}
                <hr style="border: 0; border-top: 1px solid #eee; margin: 20px 0;">
                <p style="font-size: 0.9em; color: #666;">
                    Manage your subscription: <a href="${process.env.NEXT_PUBLIC_SITE_URL}/supplier/dashboard">Supplier Dashboard</a>
                </p>
            </div>
        `,
    };

    try {
        const info = await transporter.sendMail(mailOptions);
        console.log(`Subscription update email (${updateType}) sent to ${recipientEmail}. ID: ${info.messageId}`);
        return { success: true, messageId: info.messageId };
    } catch (error: any) {
        console.error(`Error sending subscription email to ${recipientEmail}:`, error);
        return { success: false, error: error.message };
    }
}
